baseURL = "https://extendswind.top"
# title = "extendswind" 显示在右上方
title = "A Notebook of Extendswind"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = "本站原创文章遵循CC-BY 4.0版权协议，转载注明出处即可"

theme = "minimo"
#theme = "hugo-icarus-theme"
# 某些设置在data/config 目录下
#

# TOC (tableOfContents)
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

#disqusShortname = "extendswind"
disqusShortname = "extendswind"
googleAnalytics = "UA-125329544-1"

Paginate = 20
preserveTaxonomyNames = true

enableRobotsTXT = false # generate robots.txt 用于限制搜索引擎的爬虫

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "a simple blog site" # 显示在右上方的标题下 不被覆盖的话会在左方的名字下

title404 = "Nothing's here!  404 "
# A programmer or a researcher
[params.assets]
favicon = "/images/wind.jpeg"
customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )


# [params.copyright]
# prefix = ""
# holder = "extendswind"
# startYear = "2018"
# suffix = "本站原创文章遵循CC-BY 4.0版权协议，转载注明出处即可"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = false
taxonomyCloudShuffle = false
accentColor = "#cccccc"
hideMainMenu = true

[params.sidebar]
enable = true

[params.search]
client = "fuse"

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about", "sidebar_menu", "taxonomy_cloud","search"]
# sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

# [params.opengraph.facebook]
# admins = [] # array of Facebook IDs
# appID = ""
# pageID = ""
# 
# [params.opengraph.twitter]
# page = "" # Twitter page username
# 


[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "extendswind@foxmail.com"
#facebook = "MunifTanjim"
github = "extendswind"
#gitlab = "MunifTanjim"
#instagram = "MunifTanjim"
#linkedin = "muniftanjim"
#twitter = "MunifTanjim"
#telegram = "MunifTanjim"
#google_scholar = "qc6CJjYAAAAJ"

# [params.comments]
# enable = false
# 
# [params.comments.staticman]
# enable = true
# apiEndpoint = "https://api.staticman.net/v2/entry"
# maxDepth = 2
# 
# [params.comments.staticman.github]
# username = "MunifTanjim"
# repository = "minimo"
# branch = "master"

[taxonomies] # 分类
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]

[[menu.main]]
name = "Home"
weight = -10
identifier = "home"
url = "/"

[[menu.main]]
name = "Posts"
weight = -9 
identifier = "posts"
url = "/posts"

[[menu.main]]
name = "Categories"
weight = 3
identifier = "categories"
url = "/categories"

[[menu.main]]
name = "GitHub"
weight = 10
identifier = "repository"
url = "https://github.com/extendswind"

[[menu.main]]
name = "Cnblog"
weight = 11
identifier = "cnblog"
url = "https://www.cnblogs.com/fly2wind/"

[about]
title = "test"
description = "test diecription"

[blackfriday]
hrefTargetBlank = true

# [languages]
# # edit this block for your own language
# [languages.en]
# lang = "en"
# languageName = "English"
# weight = 10
# [languages.zh]
# lang = "zh"
# languageName = "Chinese"
# weight = 5
